package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * GeoBase generated by hbm2java
 */
public class GeoBase implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;

	public GeoBase() {
	}

	public GeoBase(int autoId) {
		this.autoId = autoId;
	}

	public GeoBase(int autoId, Geometry geometryData) {
		this.autoId = autoId;
		this.geometryData = geometryData;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

}
