package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * GeoCable generated by hbm2java
 */
public class GeoCable implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;
	private Long wellId;
	private Long cableId;
	private Integer voltageGrade;
	private Long ppSegmentId;
	private Integer cableDiameter;

	public GeoCable() {
	}

	public GeoCable(int autoId) {
		this.autoId = autoId;
	}

	public GeoCable(int autoId, Geometry geometryData, Long wellId,
			Long cableId, Integer voltageGrade,Long ppSegmentId,Integer cableDiameter) {
		this.autoId = autoId;
		this.geometryData = geometryData;
		this.wellId = wellId;
		this.cableId = cableId;
		this.voltageGrade = voltageGrade;
		this.ppSegmentId = ppSegmentId;
		this.cableDiameter = cableDiameter;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public Long getCableId() {
		return this.cableId;
	}

	public void setCableId(Long cableId) {
		this.cableId = cableId;
	}

	public Integer getVoltageGrade() {
		return this.voltageGrade;
	}

	public void setVoltageGrade(Integer voltageGrade) {
		this.voltageGrade = voltageGrade;
	}

	public Long getPpSegmentId() {
		return ppSegmentId;
	}

	public void setPpSegmentId(Long ppSegmentId) {
		this.ppSegmentId = ppSegmentId;
	}

	public Integer getCableDiameter() {
		return cableDiameter;
	}

	public void setCableDiameter(Integer cableDiameter) {
		this.cableDiameter = cableDiameter;
	}

}
