package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * ConnectLine generated by hbm2java
 */
public class GeoConnectLine implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;
	private Integer objectType;
	private String name;
	private Integer ZIndex;

	public GeoConnectLine() {
	}

	public GeoConnectLine(int autoId) {
		this.autoId = autoId;
	}

	public GeoConnectLine(int autoId, Geometry geometryData,
			Integer objectType, String name,Integer ZIndex) {
		this.autoId = autoId;
		this.geometryData = geometryData;
		this.objectType = objectType;
		this.name = name;
		this.ZIndex = ZIndex;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getZIndex() {
		return ZIndex;
	}

	public void setZIndex(Integer zIndex) {
		ZIndex = zIndex;
	}

}
