package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * Labletable generated by hbm2java
 */
public class GeoLabeltable implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;
	private Long wellId;
	private Long ppSegmentId; 

	public GeoLabeltable() {
	}

	public GeoLabeltable(int autoId) {
		this.autoId = autoId;
	}

	public GeoLabeltable(int autoId, Geometry geometryData, Long wellId,Long ppSegmentId) {
		this.autoId = autoId;
		this.geometryData = geometryData;
		this.wellId = wellId;
		this.ppSegmentId = ppSegmentId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public Long getPpSegmentId() {
		return ppSegmentId;
	}

	public void setPpSegmentId(Long ppSegmentId) {
		this.ppSegmentId = ppSegmentId;
	}

}
