package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * Lable generated by hbm2java
 */
public class GeoLabel implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;
	private Long wellId;
	private String cableName;
	private Long pipeHoleId;
	private Boolean isAvailable;
	private String color;
	private Long ppSegmentId;

	public GeoLabel() {
	}

	public GeoLabel(int autoId) {
		this.autoId = autoId;
	}

	public GeoLabel(int autoId, Geometry geometryData, Long wellId,
			String cableName, Long pipeHoleId, Boolean isAvailable,
			String color,Long ppSegmentId) {
		this.autoId = autoId;
		this.geometryData = geometryData;
		this.wellId = wellId;
		this.cableName = cableName;
		this.pipeHoleId = pipeHoleId;
		this.isAvailable = isAvailable;
		this.color = color;
		this.ppSegmentId = ppSegmentId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public String getCableName() {
		return this.cableName;
	}

	public void setCableName(String cableName) {
		this.cableName = cableName;
	}

	public Long getPipeHoleId() {
		return this.pipeHoleId;
	}

	public void setPipeHoleId(Long pipeHoleId) {
		this.pipeHoleId = pipeHoleId;
	}

	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Long getPpSegmentId() {
		return ppSegmentId;
	}

	public void setPpSegmentId(Long ppSegmentId) {
		this.ppSegmentId = ppSegmentId;
	}

}
