package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Point;

/**
 * PointSurvery generated by hbm2java
 */
public class GeoPointSurvery implements java.io.Serializable {

	private int autoId;
	private Geometry geometryData;
	private Long wellId;
	private Integer objectType;

	public GeoPointSurvery() {
	}

	public GeoPointSurvery(int autoId) {
		this.autoId = autoId;
	}

	public GeoPointSurvery(int autoId, Geometry geometryData, Long wellId,Integer objectType) {
		this.autoId = autoId;
		this.geometryData = geometryData;
		this.wellId = wellId;
		this.objectType = objectType;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Geometry getGeometryData() {
		return this.geometryData;
	}

	public void setGeometryData(Geometry geometryData) {
		this.geometryData = geometryData;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public Integer getObjectType() {
		return objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

}
