package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdAuxiliary generated by hbm2java
 */
public class PdAuxiliary implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Integer hostType;
	private Long hostId;
	private String auxiliaryType;
	private String auxiliaryPath;

	public PdAuxiliary() {
	}

	public PdAuxiliary(int autoId) {
		this.autoId = autoId;
	}

	public PdAuxiliary(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Integer hostType, Long hostId,
			String auxiliaryType,String auxiliaryPath) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.hostType = hostType;
		this.hostId = hostId;
		this.auxiliaryType = auxiliaryType;
		this.auxiliaryPath = auxiliaryPath;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Integer getHostType() {
		return this.hostType;
	}

	public void setHostType(Integer hostType) {
		this.hostType = hostType;
	}

	public Long getHostId() {
		return this.hostId;
	}

	public void setHostId(Long hostId) {
		this.hostId = hostId;
	}

	public String getAuxiliaryType() {
		return auxiliaryType;
	}

	public void setAuxiliaryType(String auxiliaryType) {
		this.auxiliaryType = auxiliaryType;
	}

	public String getAuxiliaryPath() {
		return auxiliaryPath;
	}

	public void setAuxiliaryPath(String auxiliaryPath) {
		this.auxiliaryPath = auxiliaryPath;
	}

}
