package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PdElCnCableSegment generated by hbm2java
 */
public class PdElCnCableSegment implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Integer voltageGrade;
	private Long startContainer;
	private Integer startContainerType;
	private Long endContainer;
	private Integer endContainerType;
	private Long belongsCableline;
	private String wirecableSegmengModel;
	private String manufacturer;
	private Date manufacturerDate;
	private Date commissioningDate;
	private String builder;
	private String assetCode;
	private String remark;
	private Integer serviceStatus;
	private String owner;
	private Integer attachmentId;
	private Integer length;
	private Integer centerTerminalCount;
	private Double ratedVoltage;
	private Double section;
	private Double currentCarryingCapacity;
	private Integer coreMaterial;
	private Integer coresCount;
	private String layingMenthod;
	private String drawingNumber;
	//private Double ratedCapacity;

	public PdElCnCableSegment() {
	}

	public PdElCnCableSegment(int autoId) {
		this.autoId = autoId;
	}

	public PdElCnCableSegment(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Integer voltageGrade,
			Long startContainer,Integer startContainerType, Long endContainer,Integer endContainerType,
			Long belongsCableline, String wirecableSegmengModel,
			String manufacturer, Date manufacturerDate, Date commissioningDate,
			String builder, String assetCode, String remark,
			Integer serviceStatus, String owner, Integer attachmentId,
			Integer length, Integer centerTerminalCount, Double ratedVoltage,
			Double section, Double currentCarryingCapacity,
			Integer coreMaterial, Integer coresCount, String layingMenthod,
			String drawingNumber) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.voltageGrade = voltageGrade;
		this.startContainer = startContainer;
		this.startContainerType = startContainerType;
		this.endContainer = endContainer;
		this.endContainerType = endContainerType;
		this.belongsCableline = belongsCableline;
		this.wirecableSegmengModel = wirecableSegmengModel;
		this.manufacturer = manufacturer;
		this.manufacturerDate = manufacturerDate;
		this.commissioningDate = commissioningDate;
		this.builder = builder;
		this.assetCode = assetCode;
		this.remark = remark;
		this.serviceStatus = serviceStatus;
		this.owner = owner;
		this.attachmentId = attachmentId;
		this.length = length;
		this.centerTerminalCount = centerTerminalCount;
		this.ratedVoltage = ratedVoltage;
		this.section = section;
		this.currentCarryingCapacity = currentCarryingCapacity;
		this.coreMaterial = coreMaterial;
		this.coresCount = coresCount;
		this.layingMenthod = layingMenthod;
		this.drawingNumber = drawingNumber;
		//this.ratedCapacity = ratedCapacity;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Integer getVoltageGrade() {
		return this.voltageGrade;
	}

	public void setVoltageGrade(Integer voltageGrade) {
		this.voltageGrade = voltageGrade;
	}

//	public Long getStartIntermission() {
//		return this.startIntermission;
//	}
//
//	public void setStartIntermission(Long startIntermission) {
//		this.startIntermission = startIntermission;
//	}
//
//	public Long getEndIntermission() {
//		return this.endIntermission;
//	}
//
//	public void setEndIntermission(Long endIntermission) {
//		this.endIntermission = endIntermission;
//	}

	public Long getBelongsCableline() {
		return this.belongsCableline;
	}

	public void setBelongsCableline(Long belongsCableline) {
		this.belongsCableline = belongsCableline;
	}

	public String getWirecableSegmengModel() {
		return this.wirecableSegmengModel;
	}

	public void setWirecableSegmengModel(String wirecableSegmengModel) {
		this.wirecableSegmengModel = wirecableSegmengModel;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public Date getManufacturerDate() {
		return this.manufacturerDate;
	}

	public void setManufacturerDate(Date manufacturerDate) {
		this.manufacturerDate = manufacturerDate;
	}

	public void setManufacturerDate(String manufacturerDate) throws Exception {
		//if(manufacturerDate.equals(""))
		this.manufacturerDate = new SimpleDateFormat("yyyy-MM-dd").parse(manufacturerDate);
//		this.manufacturerDate = manufacturerDate;
	}

	public Date getCommissioningDate() {
		return this.commissioningDate;
	}

	public void setCommissioningDate(Date commissioningDate) {
		
		this.commissioningDate = commissioningDate;
	}

	public void setCommissioningDate(String commissioningDate) throws Exception {
		//if(commissioningDate.equals(""))
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(commissioningDate);
//		this.commissioningDate = commissioningDate;
	}
	
	public String getBuilder() {
		return this.builder;
	}

	public void setBuilder(String builder) {
		this.builder = builder;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(Integer serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Integer getCenterTerminalCount() {
		return this.centerTerminalCount;
	}

	public void setCenterTerminalCount(Integer centerTerminalCount) {
		this.centerTerminalCount = centerTerminalCount;
	}

	public Double getRatedVoltage() {
		return this.ratedVoltage;
	}

	public void setRatedVoltage(Double ratedVoltage) {
		this.ratedVoltage = ratedVoltage;
	}

	public Double getSection() {
		return this.section;
	}

	public void setSection(Double section) {
		this.section = section;
	}

	public Double getCurrentCarryingCapacity() {
		return this.currentCarryingCapacity;
	}

	public void setCurrentCarryingCapacity(Double currentCarryingCapacity) {
		this.currentCarryingCapacity = currentCarryingCapacity;
	}

	public Integer getCoreMaterial() {
		return this.coreMaterial;
	}

	public void setCoreMaterial(Integer coreMaterial) {
		this.coreMaterial = coreMaterial;
	}

	public Integer getCoresCount() {
		return this.coresCount;
	}

	public void setCoresCount(Integer coresCount) {
		this.coresCount = coresCount;
	}

	public String getLayingMenthod() {
		return this.layingMenthod;
	}

	public void setLayingMenthod(String layingMenthod) {
		this.layingMenthod = layingMenthod;
	}

	public String getDrawingNumber() {
		return this.drawingNumber;
	}

	public void setDrawingNumber(String drawingNumber) {
		this.drawingNumber = drawingNumber;
	}

	public Long getStartContainer() {
		return startContainer;
	}

	public void setStartContainer(Long startContainer) {
		this.startContainer = startContainer;
	}

	public Integer getStartContainerType() {
		return startContainerType;
	}

	public void setStartContainerType(Integer startContainerType) {
		this.startContainerType = startContainerType;
	}

	public Long getEndContainer() {
		return endContainer;
	}

	public void setEndContainer(Long endContainer) {
		this.endContainer = endContainer;
	}

	public Integer getEndContainerType() {
		return endContainerType;
	}

	public void setEndContainerType(Integer endContainerType) {
		this.endContainerType = endContainerType;
	}

//	public Double getRatedCapacity() {
//		return ratedCapacity;
//	}
//
//	public void setRatedCapacity(Double ratedCapacity) {
//		this.ratedCapacity = ratedCapacity;
//	}

}
