package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PdElLnIntermission generated by hbm2java
 */
public class PdElLnIntermission implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Integer containerType;
	private Long containerId;
	private String unitCode;
	private Integer unitType;
	private Long belongsContainer;
	private Integer voltagsGrade;
	private Date commissioningDate;
	private String schedulingUnit;
	private Integer belongsWiringDiagram;

	public PdElLnIntermission() {
	}

	public PdElLnIntermission(int autoId) {
		this.autoId = autoId;
	}

	public PdElLnIntermission(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Integer containerType,
			Long containerId, String unitCode, Integer unitType,
			Long belongsContainer, Integer voltagsGrade,
			Date commissioningDate, String schedulingUnit,
			Integer belongsWiringDiagram) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.containerType = containerType;
		this.containerId = containerId;
		this.unitCode = unitCode;
		this.unitType = unitType;
		this.belongsContainer = belongsContainer;
		this.voltagsGrade = voltagsGrade;
		this.commissioningDate = commissioningDate;
		this.schedulingUnit = schedulingUnit;
		this.belongsWiringDiagram = belongsWiringDiagram;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Integer getContainerType() {
		return this.containerType;
	}

	public void setContainerType(Integer containerType) {
		this.containerType = containerType;
	}

	public Long getContainerId() {
		return this.containerId;
	}

	public void setContainerId(Long containerId) {
		this.containerId = containerId;
	}

	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	public Integer getUnitType() {
		return this.unitType;
	}

	public void setUnitType(Integer unitType) {
		this.unitType = unitType;
	}

	public Long getBelongsContainer() {
		return this.belongsContainer;
	}

	public void setBelongsContainer(Long belongsContainer) {
		this.belongsContainer = belongsContainer;
	}

	public Integer getVoltagsGrade() {
		return this.voltagsGrade;
	}

	public void setVoltagsGrade(Integer voltagsGrade) {
		this.voltagsGrade = voltagsGrade;
	}

	public Date getCommissioningDate() {
		return this.commissioningDate;
	}

	public void setCommissioningDate(Date commissioningDate) {
		this.commissioningDate = commissioningDate;
	}

	public void setCommissioningDate(String commissioningDate) throws Exception{
//		this.commissioningDate = commissioningDate;
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(commissioningDate);
	}

	public String getSchedulingUnit() {
		return this.schedulingUnit;
	}

	public void setSchedulingUnit(String schedulingUnit) {
		this.schedulingUnit = schedulingUnit;
	}

	public Integer getBelongsWiringDiagram() {
		return this.belongsWiringDiagram;
	}

	public void setBelongsWiringDiagram(Integer belongsWiringDiagram) {
		this.belongsWiringDiagram = belongsWiringDiagram;
	}

}
