package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PdElLnCableline generated by hbm2java
 */
public class PdElLnCableline implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private String runCode;
	private String operatingUnit;
	private Integer voltageGrade;
	private String switchCode;
	private Long startTransStation;
	private Date commissioningDate;
	private Integer cablelineProperties;
	private Integer cablelineType;
	private Integer cablelineLength;
	private Integer aerialcableLength;
	private Integer undergroundcableLength;
	private String builder;
	private String owner;
	private String assetCode;
	private String remark;
	private Integer serviceStatus;
	private Integer attachmentId;

	public PdElLnCableline() {
	}

	public PdElLnCableline(int autoId) {
		this.autoId = autoId;
	}

	public PdElLnCableline(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, String runCode,
			String operatingUnit, Integer voltageGrade, String switchCode,
			Long startTransStation, Date commissioningDate,
			Integer cablelineProperties, Integer cablelineType,
			Integer cablelineLength, Integer aerialcableLength,
			Integer undergroundcableLength, String builder, String owner,
			String assetCode, String remark, Integer serviceStatus,
			Integer attachmentId) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.runCode = runCode;
		this.operatingUnit = operatingUnit;
		this.voltageGrade = voltageGrade;
		this.switchCode = switchCode;
		this.startTransStation = startTransStation;
		this.commissioningDate = commissioningDate;
		this.cablelineProperties = cablelineProperties;
		this.cablelineType = cablelineType;
		this.cablelineLength = cablelineLength;
		this.aerialcableLength = aerialcableLength;
		this.undergroundcableLength = undergroundcableLength;
		this.builder = builder;
		this.owner = owner;
		this.assetCode = assetCode;
		this.remark = remark;
		this.serviceStatus = serviceStatus;
		this.attachmentId = attachmentId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public String getRunCode() {
		return this.runCode;
	}

	public void setRunCode(String runCode) {
		this.runCode = runCode;
	}

	public String getOperatingUnit() {
		return this.operatingUnit;
	}

	public void setOperatingUnit(String operatingUnit) {
		this.operatingUnit = operatingUnit;
	}

	public Integer getVoltageGrade() {
		return this.voltageGrade;
	}

	public void setVoltageGrade(Integer voltageGrade) {
		this.voltageGrade = voltageGrade;
	}

	public String getSwitchCode() {
		return this.switchCode;
	}

	public void setSwitchCode(String switchCode) {
		this.switchCode = switchCode;
	}

	public Long getStartTransStation() {
		return this.startTransStation;
	}

	public void setStartTransStation(Long startTransStation) {
		this.startTransStation = startTransStation;
	}

	public Date getCommissioningDate() {
		return this.commissioningDate;
	}

	public void setCommissioningDate(Date commissioningDate) {
		this.commissioningDate = commissioningDate;
	}

	public void setCommissioningDate(String commissioningDate) throws Exception{
//		this.commissioningDate = commissioningDate;
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(commissioningDate);
	}
	
	public Integer getCablelineProperties() {
		return this.cablelineProperties;
	}

	public void setCablelineProperties(Integer cablelineProperties) {
		this.cablelineProperties = cablelineProperties;
	}

	public Integer getCablelineType() {
		return this.cablelineType;
	}

	public void setCablelineType(Integer cablelineType) {
		this.cablelineType = cablelineType;
	}

	public Integer getCablelineLength() {
		return this.cablelineLength;
	}

	public void setCablelineLength(Integer cablelineLength) {
		this.cablelineLength = cablelineLength;
	}

	public Integer getAerialcableLength() {
		return this.aerialcableLength;
	}

	public void setAerialcableLength(Integer aerialcableLength) {
		this.aerialcableLength = aerialcableLength;
	}

	public Integer getUndergroundcableLength() {
		return this.undergroundcableLength;
	}

	public void setUndergroundcableLength(Integer undergroundcableLength) {
		this.undergroundcableLength = undergroundcableLength;
	}

	public String getBuilder() {
		return this.builder;
	}

	public void setBuilder(String builder) {
		this.builder = builder;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(Integer serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

}
