package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PdElLnWirecableSegmengV generated by hbm2java
 */
public class PdElLnWirecableSegmengV implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Integer voltageGrade;
	private Long startContainer;
	private Integer startContainerType;
	private Long endContainer;
	private Integer endContainerType;
	private Long belongsCableline;
	private String wirecableSegmengModel;
	private String manufacturer;
	private Date manufacturerDate;
	private Date commissioningDate;
	private String builder;
	private String assetCode;
	private String remark;
	private Integer serviceStatus;
	private String owner;
	private Integer attachmentId;

	public PdElLnWirecableSegmengV() {
	}

	public PdElLnWirecableSegmengV(int autoId) {
		this.autoId = autoId;
	}

	public PdElLnWirecableSegmengV(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Integer voltageGrade,
			Long startContainer, Integer startContainerType, Long endContainer,Integer endContainerType,
			Long belongsCableline, String wirecableSegmengModel,
			String manufacturer, Date manufacturerDate, Date commissioningDate,
			String builder, String assetCode, String remark,
			Integer serviceStatus, String owner, Integer attachmentId) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.voltageGrade = voltageGrade;
		this.startContainer = startContainer;
		this.startContainerType = startContainerType;
		this.endContainer = endContainer;
		this.endContainerType = endContainerType;
		this.belongsCableline = belongsCableline;
		this.wirecableSegmengModel = wirecableSegmengModel;
		this.manufacturer = manufacturer;
		this.manufacturerDate = manufacturerDate;
		this.commissioningDate = commissioningDate;
		this.builder = builder;
		this.assetCode = assetCode;
		this.remark = remark;
		this.serviceStatus = serviceStatus;
		this.owner = owner;
		this.attachmentId = attachmentId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Integer getVoltageGrade() {
		return this.voltageGrade;
	}

	public void setVoltageGrade(Integer voltageGrade) {
		this.voltageGrade = voltageGrade;
	}

//	public Long getStartIntermission() {
//		return this.startIntermission;
//	}
//
//	public void setStartIntermission(Long startIntermission) {
//		this.startIntermission = startIntermission;
//	}
//
//	public Long getEndIntermission() {
//		return this.endIntermission;
//	}
//
//	public void setEndIntermission(Long endIntermission) {
//		this.endIntermission = endIntermission;
//	}

	public Long getBelongsCableline() {
		return this.belongsCableline;
	}

	public void setBelongsCableline(Long belongsCableline) {
		this.belongsCableline = belongsCableline;
	}

	public String getWirecableSegmengModel() {
		return this.wirecableSegmengModel;
	}

	public void setWirecableSegmengModel(String wirecableSegmengModel) {
		this.wirecableSegmengModel = wirecableSegmengModel;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public Date getManufacturerDate() {
		return this.manufacturerDate;
	}

	public void setManufacturerDate(Date manufacturerDate) {
		this.manufacturerDate = manufacturerDate;
	}

	public void setManufacturerDate(String manufacturerDate) throws Exception{
//		this.manufacturerDate = manufacturerDate;
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(manufacturerDate);
	}
	public Date getCommissioningDate() {
		return this.commissioningDate;
	}

	public void setCommissioningDate(Date commissioningDate) {
		this.commissioningDate = commissioningDate;
	}

	public void setCommissioningDate(String commissioningDate) throws Exception{
//		this.commissioningDate = commissioningDate;
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(commissioningDate);
	}
	public String getBuilder() {
		return this.builder;
	}

	public void setBuilder(String builder) {
		this.builder = builder;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(Integer serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public Long getStartContainer() {
		return startContainer;
	}

	public void setStartContainer(Long startContainer) {
		this.startContainer = startContainer;
	}

	public Integer getStartContainerType() {
		return startContainerType;
	}

	public void setStartContainerType(Integer startContainerType) {
		this.startContainerType = startContainerType;
	}

	public Long getEndContainer() {
		return endContainer;
	}

	public void setEndContainer(Long endContainer) {
		this.endContainer = endContainer;
	}

	public Integer getEndContainerType() {
		return endContainerType;
	}

	public void setEndContainerType(Integer endContainerType) {
		this.endContainerType = endContainerType;
	}

}
