package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdEwPipeLineV generated by hbm2java
 */
public class PdEwPipeLineV implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Long startBuilding;
	private Integer startBuildingType;
	private Long endBuilding;
	private Integer endBuildingType;
	private Long belongsRoad;

	public PdEwPipeLineV() {
	}

	public PdEwPipeLineV(int autoId) {
		this.autoId = autoId;
	}

	public PdEwPipeLineV(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Long startBuilding,
			Integer startBuildingType, Long endBuilding,
			Integer endBuildingType, Long belongsRoad) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.startBuilding = startBuilding;
		this.startBuildingType = startBuildingType;
		this.endBuilding = endBuilding;
		this.endBuildingType = endBuildingType;
		this.belongsRoad = belongsRoad;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Long getStartBuilding() {
		return this.startBuilding;
	}

	public void setStartBuilding(Long startBuilding) {
		this.startBuilding = startBuilding;
	}

	public Integer getStartBuildingType() {
		return this.startBuildingType;
	}

	public void setStartBuildingType(Integer startBuildingType) {
		this.startBuildingType = startBuildingType;
	}

	public Long getEndBuilding() {
		return this.endBuilding;
	}

	public void setEndBuilding(Long endBuilding) {
		this.endBuilding = endBuilding;
	}

	public Integer getEndBuildingType() {
		return this.endBuildingType;
	}

	public void setEndBuildingType(Integer endBuildingType) {
		this.endBuildingType = endBuildingType;
	}

	public Long getBelongsRoad() {
		return this.belongsRoad;
	}

	public void setBelongsRoad(Long belongsRoad) {
		this.belongsRoad = belongsRoad;
	}

}
