package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PdEwPtTower generated by hbm2java
 */
public class PdEwPtTower implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private String builder;
	private String assetCode;
	private Double longitude;
	private Double latitude;
	private Double elevation;
	private String owner;
	private Long belongsRoad;
	private Integer voltageGrade;
	private Integer attachmentId;
	private String remark;
	private String towerCode;
	private Long belongsCableline;
	private String towerModel;
	private String manufacturer;
	private Date commissioningDate;
	private Integer towerProperties;
	private Integer towerMaterial;
	private Integer height;
	private Integer span;
	private Boolean highLowPressure;
	private Integer circuitCount;
	private String baseType;
	private Integer cableCount;
	private Double groundResistance;
	private Integer serviceStatus;
	private Integer depth;
	private String manufactureCode;
	private Boolean hasLamp;
	private Boolean hasCommunication;

	public PdEwPtTower() {
	}

	public PdEwPtTower(int autoId) {
		this.autoId = autoId;
	}

	public PdEwPtTower(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, String builder, String assetCode,
			Double longitude, Double latitude, Double elevation, String owner,
			Long belongsRoad, Integer voltageGrade, Integer attachmentId,
			String remark, String towerCode, Long belongsCableline,
			String towerModel, String manufacturer, Date commissioningDate,
			Integer towerProperties, Integer towerMaterial, Integer height,
			Integer span, Boolean highLowPressure, Integer circuitCount,
			String baseType, Integer cableCount, Double groundResistance,
			Integer serviceStatus, Integer depth, String manufactureCode,
			Boolean hasLamp, Boolean hasCommunication) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.builder = builder;
		this.assetCode = assetCode;
		this.longitude = longitude;
		this.latitude = latitude;
		this.elevation = elevation;
		this.owner = owner;
		this.belongsRoad = belongsRoad;
		this.voltageGrade = voltageGrade;
		this.attachmentId = attachmentId;
		this.remark = remark;
		this.towerCode = towerCode;
		this.belongsCableline = belongsCableline;
		this.towerModel = towerModel;
		this.manufacturer = manufacturer;
		this.commissioningDate = commissioningDate;
		this.towerProperties = towerProperties;
		this.towerMaterial = towerMaterial;
		this.height = height;
		this.span = span;
		this.highLowPressure = highLowPressure;
		this.circuitCount = circuitCount;
		this.baseType = baseType;
		this.cableCount = cableCount;
		this.groundResistance = groundResistance;
		this.serviceStatus = serviceStatus;
		this.depth = depth;
		this.manufactureCode = manufactureCode;
		this.hasLamp = hasLamp;
		this.hasCommunication = hasCommunication;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public String getBuilder() {
		return this.builder;
	}

	public void setBuilder(String builder) {
		this.builder = builder;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getElevation() {
		return this.elevation;
	}

	public void setElevation(Double elevation) {
		this.elevation = elevation;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Long getBelongsRoad() {
		return this.belongsRoad;
	}

	public void setBelongsRoad(Long belongsRoad) {
		this.belongsRoad = belongsRoad;
	}

	public Integer getVoltageGrade() {
		return this.voltageGrade;
	}

	public void setVoltageGrade(Integer voltageGrade) {
		this.voltageGrade = voltageGrade;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getTowerCode() {
		return this.towerCode;
	}

	public void setTowerCode(String towerCode) {
		this.towerCode = towerCode;
	}

	public Long getBelongsCableline() {
		return this.belongsCableline;
	}

	public void setBelongsCableline(Long belongsCableline) {
		this.belongsCableline = belongsCableline;
	}

	public String getTowerModel() {
		return this.towerModel;
	}

	public void setTowerModel(String towerModel) {
		this.towerModel = towerModel;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public Date getCommissioningDate() {
		return this.commissioningDate;
	}

	public void setCommissioningDate(Date commissioningDate) {
		this.commissioningDate = commissioningDate;
	}

	public void setCommissioningDate(String commissioningDate)throws Exception {
//		this.commissioningDate = commissioningDate;
		this.commissioningDate = new SimpleDateFormat("yyyy-MM-dd").parse(commissioningDate);
	}
	public Integer getTowerProperties() {
		return this.towerProperties;
	}

	public void setTowerProperties(Integer towerProperties) {
		this.towerProperties = towerProperties;
	}

	public Integer getTowerMaterial() {
		return this.towerMaterial;
	}

	public void setTowerMaterial(Integer towerMaterial) {
		this.towerMaterial = towerMaterial;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Integer getSpan() {
		return this.span;
	}

	public void setSpan(Integer span) {
		this.span = span;
	}

	public Boolean getHighLowPressure() {
		return this.highLowPressure;
	}

	public void setHighLowPressure(Boolean highLowPressure) {
		this.highLowPressure = highLowPressure;
	}

	public Integer getCircuitCount() {
		return this.circuitCount;
	}

	public void setCircuitCount(Integer circuitCount) {
		this.circuitCount = circuitCount;
	}

	public String getBaseType() {
		return this.baseType;
	}

	public void setBaseType(String baseType) {
		this.baseType = baseType;
	}

	public Integer getCableCount() {
		return this.cableCount;
	}

	public void setCableCount(Integer cableCount) {
		this.cableCount = cableCount;
	}

	public Double getGroundResistance() {
		return this.groundResistance;
	}

	public void setGroundResistance(Double groundResistance) {
		this.groundResistance = groundResistance;
	}

	public Integer getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(Integer serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public Integer getDepth() {
		return this.depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	public String getManufactureCode() {
		return this.manufactureCode;
	}

	public void setManufactureCode(String manufactureCode) {
		this.manufactureCode = manufactureCode;
	}

	public Boolean getHasLamp() {
		return this.hasLamp;
	}

	public void setHasLamp(Boolean hasLamp) {
		this.hasLamp = hasLamp;
	}

	public Boolean getHasCommunication() {
		return this.hasCommunication;
	}

	public void setHasCommunication(Boolean hasCommunication) {
		this.hasCommunication = hasCommunication;
	}

}
