package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdObjectType generated by hbm2java
 */
public class PdObjectType implements java.io.Serializable {

	private int typeId;
	private String typeName;
	private String typeCode;
	private Integer upbelongType;
	private Integer downbelongType;

	public PdObjectType() {
	}

	public PdObjectType(int typeId) {
		this.typeId = typeId;
	}

	public PdObjectType(int typeId, String typeName, String typeCode,
			Integer upbelongType, Integer downbelongType) {
		this.typeId = typeId;
		this.typeName = typeName;
		this.typeCode = typeCode;
		this.upbelongType = upbelongType;
		this.downbelongType = downbelongType;
	}

	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public Integer getUpbelongType() {
		return this.upbelongType;
	}

	public void setUpbelongType(Integer upbelongType) {
		this.upbelongType = upbelongType;
	}

	public Integer getDownbelongType() {
		return this.downbelongType;
	}

	public void setDownbelongType(Integer downbelongType) {
		this.downbelongType = downbelongType;
	}

}
