package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdPipeHole generated by hbm2java
 */
public class PdPipeHole implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Long wellId;
	private Long mirrorWellId;
	private Long profileId;
	private Long mirrorProfileId;//≤ª”√
	private String pipeCode;
	private Float coordinateX;
	private Float deep;
	private Float pipeDiameter;
	private String material;
	private Long wirecableSegmentId;
	private Boolean isAvailable;
	private Integer photoId;
	private Long ppSegmentId;
	
	public PdPipeHole() {
	}

	public PdPipeHole(int autoId) {
		this.autoId = autoId;
	}

	public PdPipeHole(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Long wellId, Long mirrorWellId,Long profileId,
			Long mirrorProfileId,String pipeCode, Float coordinateX, Float deep, Float pipeDiameter,
			String material, Long wirecableSegmentId, Boolean isAvailable,
			Integer photoId,Long ppSegmentId) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.wellId = wellId;
		this.mirrorWellId = mirrorWellId;
		this.mirrorProfileId = mirrorProfileId;
		this.profileId = profileId;
		this.pipeCode = pipeCode;
		this.coordinateX = coordinateX;
		this.deep = deep;
		this.pipeDiameter = pipeDiameter;
		this.material = material;
		this.wirecableSegmentId = wirecableSegmentId;
		this.isAvailable = isAvailable;
		this.photoId = photoId;
		this.ppSegmentId = ppSegmentId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public Long getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Long profileId) {
		this.profileId = profileId;
	}

	public String getPipeCode() {
		return this.pipeCode;
	}

	public void setPipeCode(String pipeCode) {
		this.pipeCode = pipeCode;
	}

	public Float getCoordinateX() {
		return this.coordinateX;
	}

	public void setCoordinateX(Float coordinateX) {
		this.coordinateX = coordinateX;
	}

	public Float getDeep() {
		return this.deep;
	}

	public void setDeep(Float deep) {
		this.deep = deep;
	}

	public Float getPipeDiameter() {
		return this.pipeDiameter;
	}

	public void setPipeDiameter(Float pipeDiameter) {
		this.pipeDiameter = pipeDiameter;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public Long getWirecableSegmentId() {
		return this.wirecableSegmentId;
	}

	public void setWirecableSegmentId(Long wirecableSegmentId) {
		this.wirecableSegmentId = wirecableSegmentId;
	}

	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	public Long getPpSegmentId() {
		return ppSegmentId;
	}

	public void setPpSegmentId(Long ppSegmentId) {
		this.ppSegmentId = ppSegmentId;
	}

	public Long getMirrorWellId() {
		return mirrorWellId;
	}

	public void setMirrorWellId(Long mirrorWellId) {
		this.mirrorWellId = mirrorWellId;
	}

	public Long getMirrorProfileId() {
		return mirrorProfileId;
	}

	public void setMirrorProfileId(Long mirrorProfileId) {
		this.mirrorProfileId = mirrorProfileId;
	}

}
