package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdTunnel generated by hbm2java
 */
public class PdPipeProfile implements java.io.Serializable {

	private int autoId;
	private Long staticId;
	private String name;
	private Integer objectType;
	private Integer rfid;
	private Long wellId;
	private Long mirrorWellId;
	private Long profileId;
	private Long mirrorProfileId;
	private Float profileWidth;
	private Float profileHigh;
	private Integer pipeNum;
	private Integer pipeStartId;
	private Integer photoId;
	private Float startX;
	private Float startY;
	private Float spaceX;
	private Float spaceY;
	private Long ppSegmentId;

	public PdPipeProfile() {
	}

	public PdPipeProfile(int autoId) {
		this.autoId = autoId;
	}

	public PdPipeProfile(int autoId, Long staticId, String name,
			Integer objectType, Integer rfid, Long wellId, Long mirrorWellId,Long profileId,
			Long mirrorProfileId,Float profileWidth, Float profileHigh, Integer pipeNum,
			Integer pipeStartId, Integer photoId, Float startX, Float startY,
			Float spaceX, Float spaceY,Long ppSegmentId) {
		this.autoId = autoId;
		this.staticId = staticId;
		this.name = name;
		this.objectType = objectType;
		this.rfid = rfid;
		this.wellId = wellId;
		this.profileId = profileId;
		this.profileWidth = profileWidth;
		this.profileHigh = profileHigh;
		this.pipeNum = pipeNum;
		this.pipeStartId = pipeStartId;
		this.photoId = photoId;
		this.startX = startX;
		this.startY = startY;
		this.spaceX = spaceX;
		this.spaceY = spaceY;
		this.ppSegmentId = ppSegmentId;
		this.mirrorWellId = mirrorWellId;
		this.mirrorProfileId = mirrorProfileId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Long getStaticId() {
		return this.staticId;
	}

	public void setStaticId(Long staticId) {
		this.staticId = staticId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	public Integer getRfid() {
		return this.rfid;
	}

	public void setRfid(Integer rfid) {
		this.rfid = rfid;
	}

	public Long getWellId() {
		return this.wellId;
	}

	public void setWellId(Long wellId) {
		this.wellId = wellId;
	}

	public Long getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Long profileId) {
		this.profileId = profileId;
	}

	public Float getProfileWidth() {
		return this.profileWidth;
	}

	public void setProfileWidth(Float profileWidth) {
		this.profileWidth = profileWidth;
	}

	public Float getProfileHigh() {
		return this.profileHigh;
	}

	public void setProfileHigh(Float profileHigh) {
		this.profileHigh = profileHigh;
	}

	public Integer getPipeNum() {
		return this.pipeNum;
	}

	public void setPipeNum(Integer pipeNum) {
		this.pipeNum = pipeNum;
	}

	public Integer getPipeStartId() {
		return this.pipeStartId;
	}

	public void setPipeStartId(Integer pipeStartId) {
		this.pipeStartId = pipeStartId;
	}

	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	public Float getStartX() {
		return this.startX;
	}

	public void setStartX(Float startX) {
		this.startX = startX;
	}

	public Float getStartY() {
		return this.startY;
	}

	public void setStartY(Float startY) {
		this.startY = startY;
	}

	public Float getSpaceX() {
		return this.spaceX;
	}

	public void setSpaceX(Float spaceX) {
		this.spaceX = spaceX;
	}

	public Float getSpaceY() {
		return this.spaceY;
	}

	public void setSpaceY(Float spaceY) {
		this.spaceY = spaceY;
	}

	public Long getPpSegmentId() {
		return ppSegmentId;
	}

	public void setPpSegmentId(Long ppSegmentId) {
		this.ppSegmentId = ppSegmentId;
	}

	public Long getMirrorWellId() {
		return mirrorWellId;
	}

	public void setMirrorWellId(Long mirrorWellId) {
		this.mirrorWellId = mirrorWellId;
	}

	public Long getMirrorProfileId() {
		return mirrorProfileId;
	}

	public void setMirrorProfileId(Long mirrorProfileId) {
		this.mirrorProfileId = mirrorProfileId;
	}

}
