package org.resource.objectclass;

// Generated Sep 26, 2013 2:25:34 PM by Hibernate Tools 4.0.0

/**
 * PdWirecablToPipeSegment generated by hbm2java
 */
public class PdWirecablToPipeSegment implements java.io.Serializable {

	private PdWirecablToPipeSegmentId id;

	public PdWirecablToPipeSegment() {
	}

	public PdWirecablToPipeSegment(PdWirecablToPipeSegmentId id) {
		this.id = id;
	}

	public PdWirecablToPipeSegmentId getId() {
		return this.id;
	}

	public void setId(PdWirecablToPipeSegmentId id) {
		this.id = id;
	}

}
